# -*- coding: utf-8 -*-
"""ArkademyTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Skl-Zk-iSPPfrB1QtTREZF4I-rCcXi4
"""

import  json

class biodata:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myname(self):
    print(self.name)

bio = biodata("Ghalyatama Ikram Fauzi", 21)

mybio = {
    "address": "Tanjung Senang, Bandar Lampung",
    "hobbies": ["Basket","Main Game","Desain"],
    "is_married": False,
    "list_school": [
                    {"SD": "SD Al-Azhar","year_in": "2004","year_out": "2010","major": "null"},
                    {"SMP": "SMPN 29 Bandar Lampung","year_in": "2010","year_out": "2013", "major": "null"},
                    {"SMA": "YP Unila","year_in": "2013","year_out": "2016", "major": "IPA"}
    ],
    "skills": [
               {"skill_name": "desain grafis","level": "beginner"},
               {"skill_name": "frontend developer","level": "beginner"},
               {"skill_name": "data mining","level": "beginner"}
    ],
    "interest_in_coding": True

}

print(json.dumps(mybio, indent=4))

mybio['name'] = bio.name
mybio["age"] = bio.age

print(json.dumps(mybio, indent=4))